import {
  AlertSeverity,
  AlertStatus,
  AlertType,
  Category,
  EventStatus,
  MeetingStatus,
  MeetingType,
  PrismaClient,
  SourceSection,
  SourceType,
  SubmissionType,
  SubmittedEventStatus,
  VolunteerStatus,
} from "@prisma/client";

const prisma = new PrismaClient();

const sources = [
  {
    name: "City of Hiram official site",
    url: "https://www.cityofhiramga.gov/",
    type: SourceType.WEBSITE,
    section: SourceSection.EVENTS,
    city: "Hiram",
    county: "Paulding",
    active: true,
    scrapeFrequency: "daily",
    notes: "Working scraper target for local events and notices.",
  },
  {
    name: "City of Hiram public meetings",
    url: "https://www.cityofhiramga.gov/",
    type: SourceType.GOVERNMENT,
    section: SourceSection.MEETINGS,
    city: "Hiram",
    county: "Paulding",
    active: true,
    scrapeFrequency: "manual",
    notes: "Manual entry supported for agendas, minutes, and videos.",
  },
  {
    name: "City of Hiram Facebook",
    url: "https://www.facebook.com/CityofHiram/",
    type: SourceType.FACEBOOK,
    section: SourceSection.EVENTS,
    city: "Hiram",
    county: "Paulding",
    active: true,
    scrapeFrequency: "manual",
    notes: "Manual review needed. Facebook is not used as a core automated source.",
  },
  {
    name: "City of Dallas official events page",
    url: "https://www.dallasga.gov/community/page/upcoming-events",
    type: SourceType.WEBSITE,
    section: SourceSection.EVENTS,
    city: "Dallas",
    county: "Paulding",
    active: true,
    scrapeFrequency: "daily",
    notes: "Working scraper target for city events.",
  },
  {
    name: "Downtown Dallas / MyDallasGA",
    url: "https://www.mydallasga.com/",
    type: SourceType.WEBSITE,
    section: SourceSection.ACTIVITIES,
    city: "Dallas",
    county: "Paulding",
    active: true,
    scrapeFrequency: "daily",
    notes: "Downtown activity source used for events and activity ideas.",
  },
  {
    name: "City of Dallas public meetings",
    url: "https://www.dallasga.gov/",
    type: SourceType.GOVERNMENT,
    section: SourceSection.MEETINGS,
    city: "Dallas",
    county: "Paulding",
    active: true,
    scrapeFrequency: "manual",
    notes: "Manual meeting management supported in admin.",
  },
  {
    name: "City of Dallas Facebook",
    url: "https://www.facebook.com/dallas.georgia/",
    type: SourceType.FACEBOOK,
    section: SourceSection.EVENTS,
    city: "Dallas",
    county: "Paulding",
    active: true,
    scrapeFrequency: "manual",
    notes: "Manual review needed.",
  },
  {
    name: "MyDallasGA Facebook",
    url: "https://www.facebook.com/mydallasga/",
    type: SourceType.FACEBOOK,
    section: SourceSection.ACTIVITIES,
    city: "Dallas",
    county: "Paulding",
    active: true,
    scrapeFrequency: "manual",
    notes: "Manual review needed.",
  },
  {
    name: "City of Rockmart official site",
    url: "https://www.rockmart-ga.gov/",
    type: SourceType.WEBSITE,
    section: SourceSection.EVENTS,
    city: "Rockmart",
    county: "Polk",
    active: true,
    scrapeFrequency: "daily",
    notes: "Working scraper target for city events.",
  },
  {
    name: "City of Rockmart public meetings",
    url: "https://www.rockmart-ga.gov/",
    type: SourceType.GOVERNMENT,
    section: SourceSection.MEETINGS,
    city: "Rockmart",
    county: "Polk",
    active: true,
    scrapeFrequency: "manual",
    notes: "Manual entry for public meetings is enabled.",
  },
  {
    name: "City of Rockmart Facebook",
    url: "https://www.facebook.com/CityofRockmart/",
    type: SourceType.FACEBOOK,
    section: SourceSection.EVENTS,
    city: "Rockmart",
    county: "Polk",
    active: true,
    scrapeFrequency: "manual",
    notes: "Manual review needed.",
  },
  {
    name: "City of Cedartown official site",
    url: "https://cedartowngeorgia.gov/",
    type: SourceType.WEBSITE,
    section: SourceSection.EVENTS,
    city: "Cedartown",
    county: "Polk",
    active: true,
    scrapeFrequency: "daily",
    notes: "Cataloged official city source.",
  },
  {
    name: "Downtown Cedartown events page",
    url: "https://www.downtowncedartown.com/calendar-of-events-c1qeb",
    type: SourceType.CALENDAR,
    section: SourceSection.EVENTS,
    city: "Cedartown",
    county: "Polk",
    active: true,
    scrapeFrequency: "daily",
    notes: "Working scraper target for downtown events.",
  },
  {
    name: "City of Cedartown public meetings",
    url: "https://cedartowngeorgia.gov/",
    type: SourceType.GOVERNMENT,
    section: SourceSection.MEETINGS,
    city: "Cedartown",
    county: "Polk",
    active: true,
    scrapeFrequency: "manual",
    notes: "Manual meeting management supported.",
  },
  {
    name: "City of Cedartown Facebook",
    url: "https://www.facebook.com/CityofCedartown/",
    type: SourceType.FACEBOOK,
    section: SourceSection.EVENTS,
    city: "Cedartown",
    county: "Polk",
    active: true,
    scrapeFrequency: "manual",
    notes: "Manual review needed.",
  },
  {
    name: "Paulding County Parks & Recreation",
    url: "https://www.paulding.gov/170/Parks-Recreation-Cultural-Affairs",
    type: SourceType.RECREATION,
    section: SourceSection.ACTIVITIES,
    city: null,
    county: "Paulding",
    active: true,
    scrapeFrequency: "weekly",
    notes: "Landing page for programs and recreation updates.",
  },
  {
    name: "Paulding County Parks calendar",
    url: "https://paulding.gov/calendar.aspx?CID=62",
    type: SourceType.CALENDAR,
    section: SourceSection.EVENTS,
    city: null,
    county: "Paulding",
    active: true,
    scrapeFrequency: "daily",
    notes: "Working scraper target for parks calendar items.",
  },
  {
    name: "Paulding County recreation registration/events",
    url: "https://recreation.paulding.gov/",
    type: SourceType.RECREATION,
    section: SourceSection.ACTIVITIES,
    city: null,
    county: "Paulding",
    active: true,
    scrapeFrequency: "weekly",
    notes: "Tracked for future enrichment.",
  },
  {
    name: "Paulding County Parks Facebook",
    url: "https://www.facebook.com/pauldingparksandrec/",
    type: SourceType.FACEBOOK,
    section: SourceSection.ACTIVITIES,
    city: null,
    county: "Paulding",
    active: true,
    scrapeFrequency: "manual",
    notes: "Manual review needed.",
  },
  {
    name: "Paulding County Sheriff Facebook",
    url: "https://www.facebook.com/PauldingSheriff/",
    type: SourceType.SHERIFF,
    section: SourceSection.ALERTS,
    city: null,
    county: "Paulding",
    active: true,
    scrapeFrequency: "manual",
    notes: "Manual review needed for public safety alerts.",
  },
  {
    name: "Hiram Police Facebook",
    url: "https://www.facebook.com/HiramPolice/",
    type: SourceType.POLICE,
    section: SourceSection.ALERTS,
    city: "Hiram",
    county: "Paulding",
    active: true,
    scrapeFrequency: "manual",
    notes: "Manual review needed for alerts and notices.",
  },
  {
    name: "Dallas Police Facebook",
    url: "https://www.facebook.com/DallasGAPolice/",
    type: SourceType.POLICE,
    section: SourceSection.ALERTS,
    city: "Dallas",
    county: "Paulding",
    active: true,
    scrapeFrequency: "manual",
    notes: "Manual review needed for alerts and notices.",
  },
  {
    name: "Rockmart Police Facebook",
    url: "https://www.facebook.com/RockmartPoliceDepartment/",
    type: SourceType.POLICE,
    section: SourceSection.ALERTS,
    city: "Rockmart",
    county: "Polk",
    active: true,
    scrapeFrequency: "manual",
    notes: "Manual review needed for alerts and notices.",
  },
  {
    name: "Cedartown Police Facebook",
    url: "https://www.facebook.com/CedartownPoliceDepartment/",
    type: SourceType.POLICE,
    section: SourceSection.ALERTS,
    city: "Cedartown",
    county: "Polk",
    active: true,
    scrapeFrequency: "manual",
    notes: "Manual review needed for alerts and notices.",
  },
  {
    name: "What’s Happening in Dallas, Georgia Facebook",
    url: "https://www.facebook.com/",
    type: SourceType.FACEBOOK,
    section: SourceSection.ACTIVITIES,
    city: "Dallas",
    county: "Paulding",
    active: true,
    scrapeFrequency: "manual",
    notes: "Community activity source for manual review.",
  },
  {
    name: "The Hopp Frogg Music Facebook",
    url: "https://www.facebook.com/",
    type: SourceType.MUSIC_VENUE,
    section: SourceSection.ACTIVITIES,
    city: "Rockmart",
    county: "Polk",
    active: true,
    scrapeFrequency: "manual",
    notes: "Music venue source for manual review.",
  },
  {
    name: "Pizza Shack Facebook",
    url: "https://www.facebook.com/",
    type: SourceType.RESTAURANT,
    section: SourceSection.ACTIVITIES,
    city: "Rockmart",
    county: "Polk",
    active: true,
    scrapeFrequency: "manual",
    notes: "Restaurant activity source for manual review.",
  },
  {
    name: "Paulding County Board of Commissioners meetings",
    url: "https://www.paulding.gov/",
    type: SourceType.GOVERNMENT,
    section: SourceSection.MEETINGS,
    city: null,
    county: "Paulding",
    active: true,
    scrapeFrequency: "manual",
    notes: "Manual meeting entry supported.",
  },
  {
    name: "Polk County Board of Commissioners meetings",
    url: "https://www.polkga.org/",
    type: SourceType.GOVERNMENT,
    section: SourceSection.MEETINGS,
    city: null,
    county: "Polk",
    active: true,
    scrapeFrequency: "manual",
    notes: "Manual meeting entry supported.",
  },
  {
    name: "Cobb County PARKS",
    url: "https://www.cobbcounty.gov/parks",
    type: SourceType.RECREATION,
    section: SourceSection.ACTIVITIES,
    city: null,
    county: "Cobb",
    active: true,
    scrapeFrequency: "weekly",
    notes: "Primary county parks information source.",
  },
  {
    name: "Cobb County PARKS programs",
    url: "https://www.cobbcounty.gov/parks/programs",
    type: SourceType.RECREATION,
    section: SourceSection.ACTIVITIES,
    city: null,
    county: "Cobb",
    active: true,
    scrapeFrequency: "weekly",
    notes: "Program listings and recurring parks activities.",
  },
  {
    name: "Cobb County recreation catalog",
    url: "https://secure.rec1.com/GA/cobb-county-ga/catalog",
    type: SourceType.RECREATION,
    section: SourceSection.ACTIVITIES,
    city: null,
    county: "Cobb",
    active: true,
    scrapeFrequency: "weekly",
    notes: "Rec1 catalog source for recreation classes and events.",
  },
  {
    name: "Cobb County events",
    url: "https://www.cobbcountyevents.com/",
    type: SourceType.CALENDAR,
    section: SourceSection.EVENTS,
    city: null,
    county: "Cobb",
    active: true,
    scrapeFrequency: "daily",
    notes: "Countywide event aggregator with subpages for multiple cities.",
  },
  {
    name: "Cobb County Government Facebook",
    url: "https://www.facebook.com/CobbCountyGovernment",
    type: SourceType.FACEBOOK,
    section: SourceSection.ALERTS,
    city: null,
    county: "Cobb",
    active: true,
    scrapeFrequency: "manual",
    notes: "Manual review source for county updates and notices.",
  },
  {
    name: "Cobb PARKS Instagram/manual source",
    url: "https://www.instagram.com/explorecobbparks/",
    type: SourceType.MANUAL,
    section: SourceSection.ACTIVITIES,
    city: null,
    county: "Cobb",
    active: true,
    scrapeFrequency: "manual",
    notes: "Instagram/manual review source only.",
  },
  {
    name: "Bartow County official site",
    url: "https://www.bartowcountyga.gov/",
    type: SourceType.GOVERNMENT,
    section: SourceSection.MEETINGS,
    city: null,
    county: "Bartow",
    active: true,
    scrapeFrequency: "manual",
    notes: "County government source with public information and meeting links.",
  },
  {
    name: "Bartow County Parks and Recreation",
    url: "https://www.bartowcountyga.gov/departments/parksandrecreation/index.php",
    type: SourceType.RECREATION,
    section: SourceSection.ACTIVITIES,
    city: null,
    county: "Bartow",
    active: true,
    scrapeFrequency: "weekly",
    notes: "County recreation landing page.",
  },
  {
    name: "Bartow County recreation catalog",
    url: "https://secure.rec1.com/GA/bartow-county/catalog",
    type: SourceType.RECREATION,
    section: SourceSection.ACTIVITIES,
    city: null,
    county: "Bartow",
    active: true,
    scrapeFrequency: "weekly",
    notes: "Rec1 recreation catalog for classes and leagues.",
  },
  {
    name: "Bartow County Parks and Recreation Facebook",
    url: "https://www.facebook.com/p/Bartow-County-Parks-and-Recreation-100064290865426/",
    type: SourceType.FACEBOOK,
    section: SourceSection.ACTIVITIES,
    city: null,
    county: "Bartow",
    active: true,
    scrapeFrequency: "manual",
    notes: "Manual review source only.",
  },
  {
    name: "Cherokee Recreation and Parks",
    url: "https://www.cherokeecountyga.gov/Cherokee-Recreation-and-Parks-Agency/",
    type: SourceType.RECREATION,
    section: SourceSection.ACTIVITIES,
    city: null,
    county: "Cherokee",
    active: true,
    scrapeFrequency: "weekly",
    notes: "County recreation source.",
  },
  {
    name: "Cherokee Recreation and Parks catalog",
    url: "https://secure.rec1.com/GA/cherokee-recreation-parks/catalog",
    type: SourceType.RECREATION,
    section: SourceSection.ACTIVITIES,
    city: null,
    county: "Cherokee",
    active: true,
    scrapeFrequency: "weekly",
    notes: "Rec1 catalog for Cherokee recreation programs.",
  },
  {
    name: "Cherokee County events and meetings",
    url: "https://cherokeega.com/cherokee-county-events.php",
    type: SourceType.CALENDAR,
    section: SourceSection.MEETINGS,
    city: null,
    county: "Cherokee",
    active: true,
    scrapeFrequency: "daily",
    notes: "Primary county source for official events and meeting notices.",
  },
  {
    name: "Cherokee Recreation and Parks Facebook",
    url: "https://www.facebook.com/playcherokee/",
    type: SourceType.FACEBOOK,
    section: SourceSection.ACTIVITIES,
    city: null,
    county: "Cherokee",
    active: true,
    scrapeFrequency: "manual",
    notes: "Manual review source only.",
  },
  {
    name: "City of Woodstock special events",
    url: "https://www.woodstockga.gov/your_government/departments/parks_and_recreation/special_events.php",
    type: SourceType.WEBSITE,
    section: SourceSection.EVENTS,
    city: "Woodstock",
    county: "Cherokee",
    active: true,
    scrapeFrequency: "daily",
    notes: "Official city special events source.",
  },
  {
    name: "Woodstock RecDesk calendar",
    url: "https://woodstock.recdesk.com/Community/Calendar",
    type: SourceType.CALENDAR,
    section: SourceSection.ACTIVITIES,
    city: "Woodstock",
    county: "Cherokee",
    active: true,
    scrapeFrequency: "daily",
    notes: "Recreation calendar source for city programs.",
  },
  {
    name: "Visit Woodstock events",
    url: "https://visitwoodstockga.com/events/",
    type: SourceType.CALENDAR,
    section: SourceSection.EVENTS,
    city: "Woodstock",
    county: "Cherokee",
    active: true,
    scrapeFrequency: "daily",
    notes: "Tourism and downtown events source.",
  },
  {
    name: "Downtown Woodstock Facebook",
    url: "https://www.facebook.com/dtwoodstock/",
    type: SourceType.FACEBOOK,
    section: SourceSection.EVENTS,
    city: "Woodstock",
    county: "Cherokee",
    active: true,
    scrapeFrequency: "manual",
    notes: "Manual review source only.",
  },
  {
    name: "Rome Georgia events",
    url: "https://romegeorgia.org/event/",
    type: SourceType.CALENDAR,
    section: SourceSection.EVENTS,
    city: "Rome",
    county: "Bartow",
    active: true,
    scrapeFrequency: "daily",
    notes: "Tourism events source.",
  },
  {
    name: "City of Rome calendar",
    url: "https://www.romega.us/Calendar/home",
    type: SourceType.CALENDAR,
    section: SourceSection.EVENTS,
    city: "Rome",
    county: "Bartow",
    active: true,
    scrapeFrequency: "daily",
    notes: "Official city calendar source.",
  },
  {
    name: "Rome official site",
    url: "https://www.romega.us/",
    type: SourceType.GOVERNMENT,
    section: SourceSection.MEETINGS,
    city: "Rome",
    county: "Bartow",
    active: true,
    scrapeFrequency: "manual",
    notes: "Official city site with meeting and notices support.",
  },
  {
    name: "Georgia’s Rome Facebook",
    url: "https://www.facebook.com/RomeGeorgia/",
    type: SourceType.FACEBOOK,
    section: SourceSection.EVENTS,
    city: "Rome",
    county: "Bartow",
    active: true,
    scrapeFrequency: "manual",
    notes: "Manual review source only.",
  },
  {
    name: "City of Canton events list",
    url: "https://www.cantonga.gov/our-city/advanced-components/list-detail-pages/calendar-meeting-list",
    type: SourceType.CALENDAR,
    section: SourceSection.EVENTS,
    city: "Canton",
    county: "Cherokee",
    active: true,
    scrapeFrequency: "daily",
    notes: "Official city events and meetings list.",
  },
  {
    name: "City of Canton calendar",
    url: "https://www.cantonga.gov/our-city/city-calendar",
    type: SourceType.CALENDAR,
    section: SourceSection.MEETINGS,
    city: "Canton",
    county: "Cherokee",
    active: true,
    scrapeFrequency: "daily",
    notes: "Official city calendar for meetings and public notices.",
  },
  {
    name: "Explore Canton events",
    url: "https://explorecantonga.com/events/",
    type: SourceType.CALENDAR,
    section: SourceSection.EVENTS,
    city: "Canton",
    county: "Cherokee",
    active: true,
    scrapeFrequency: "daily",
    notes: "Tourism and community events source.",
  },
  {
    name: "Explore Canton Facebook",
    url: "https://www.facebook.com/explorecantonga/",
    type: SourceType.FACEBOOK,
    section: SourceSection.EVENTS,
    city: "Canton",
    county: "Cherokee",
    active: true,
    scrapeFrequency: "manual",
    notes: "Manual review source only.",
  },
  {
    name: "The Mill on Etowah events",
    url: "https://www.etowahmill.com/events",
    type: SourceType.WEBSITE,
    section: SourceSection.EVENTS,
    city: "Canton",
    county: "Cherokee",
    active: true,
    scrapeFrequency: "weekly",
    notes: "Venue event source that may include markets and community gatherings.",
  },
  {
    name: "City of Adairsville calendar",
    url: "https://www.adairsvillega.net/calendar.php",
    type: SourceType.CALENDAR,
    section: SourceSection.MEETINGS,
    city: "Adairsville",
    county: "Bartow",
    active: true,
    scrapeFrequency: "daily",
    notes: "Official city calendar source.",
  },
  {
    name: "City of Adairsville events",
    url: "https://www.adairsvillega.net/community/events/index.php",
    type: SourceType.WEBSITE,
    section: SourceSection.EVENTS,
    city: "Adairsville",
    county: "Bartow",
    active: true,
    scrapeFrequency: "daily",
    notes: "Official city events source.",
  },
  {
    name: "City of Adairsville Facebook",
    url: "https://www.facebook.com/CityofAdairsville306/",
    type: SourceType.FACEBOOK,
    section: SourceSection.EVENTS,
    city: "Adairsville",
    county: "Bartow",
    active: true,
    scrapeFrequency: "manual",
    notes: "Manual review source only.",
  },
  {
    name: "City of Marietta calendar",
    url: "https://www.mariettaga.gov/Calendar.aspx",
    type: SourceType.CALENDAR,
    section: SourceSection.MEETINGS,
    city: "Marietta",
    county: "Cobb",
    active: true,
    scrapeFrequency: "daily",
    notes: "Official calendar for city meetings and public events.",
  },
  {
    name: "City of Marietta special events",
    url: "https://www.mariettaga.gov/188/Special-Events",
    type: SourceType.WEBSITE,
    section: SourceSection.EVENTS,
    city: "Marietta",
    county: "Cobb",
    active: true,
    scrapeFrequency: "daily",
    notes: "Official city special events source.",
  },
  {
    name: "Visit Marietta events",
    url: "https://visitmariettaga.com/events/",
    type: SourceType.CALENDAR,
    section: SourceSection.EVENTS,
    city: "Marietta",
    county: "Cobb",
    active: true,
    scrapeFrequency: "daily",
    notes: "Tourism and square events source.",
  },
  {
    name: "Marietta.com calendar",
    url: "https://www.marietta.com/calendar-of-events",
    type: SourceType.CALENDAR,
    section: SourceSection.EVENTS,
    city: "Marietta",
    county: "Cobb",
    active: true,
    scrapeFrequency: "weekly",
    notes: "Community calendar source.",
  },
  {
    name: "City of Acworth events",
    url: "https://acworth-ga.gov/acworth-city-events/",
    type: SourceType.WEBSITE,
    section: SourceSection.EVENTS,
    city: "Acworth",
    county: "Cobb",
    active: true,
    scrapeFrequency: "daily",
    notes: "Official city events source.",
  },
  {
    name: "City of Acworth official site",
    url: "https://acworth-ga.gov/",
    type: SourceType.GOVERNMENT,
    section: SourceSection.MEETINGS,
    city: "Acworth",
    county: "Cobb",
    active: true,
    scrapeFrequency: "manual",
    notes: "Official city site for notices and meeting support.",
  },
  {
    name: "Acworth Tourism events",
    url: "https://acworthtourism.org/acworth-events/",
    type: SourceType.CALENDAR,
    section: SourceSection.EVENTS,
    city: "Acworth",
    county: "Cobb",
    active: true,
    scrapeFrequency: "daily",
    notes: "Tourism and destination events source.",
  },
  {
    name: "Acworth.com calendar",
    url: "https://www.acworth.com/calendar-of-events/",
    type: SourceType.CALENDAR,
    section: SourceSection.EVENTS,
    city: "Acworth",
    county: "Cobb",
    active: true,
    scrapeFrequency: "weekly",
    notes: "Community calendar source.",
  },
  {
    name: "City of Kennesaw official site",
    url: "https://www.kennesaw-ga.gov/",
    type: SourceType.GOVERNMENT,
    section: SourceSection.MEETINGS,
    city: "Kennesaw",
    county: "Cobb",
    active: true,
    scrapeFrequency: "manual",
    notes: "Official site for city notices and meeting support.",
  },
  {
    name: "Kennesaw Parks and Recreation special events",
    url: "https://www.kennesaw-ga.gov/parks-and-recreation/special-events/",
    type: SourceType.RECREATION,
    section: SourceSection.EVENTS,
    city: "Kennesaw",
    county: "Cobb",
    active: true,
    scrapeFrequency: "daily",
    notes: "Official special events source for parks and recreation.",
  },
  {
    name: "Kennesaw calendar",
    url: "https://www.kennesaw.com/calendar-of-events/",
    type: SourceType.CALENDAR,
    section: SourceSection.EVENTS,
    city: "Kennesaw",
    county: "Cobb",
    active: true,
    scrapeFrequency: "weekly",
    notes: "Community events calendar source.",
  },
  {
    name: "Downtown Kennesaw",
    url: "https://kennesawdowntown.com/",
    type: SourceType.WEBSITE,
    section: SourceSection.EVENTS,
    city: "Kennesaw",
    county: "Cobb",
    active: true,
    scrapeFrequency: "weekly",
    notes: "Downtown events and merchant activity source.",
  },
  {
    name: "City of Smyrna calendar",
    url: "https://www.smyrnaga.gov/departments/advanced-components/calendar-month-view",
    type: SourceType.CALENDAR,
    section: SourceSection.MEETINGS,
    city: "Smyrna",
    county: "Cobb",
    active: true,
    scrapeFrequency: "daily",
    notes: "Official city calendar for meetings and public events.",
  },
  {
    name: "City of Smyrna community relations",
    url: "https://www.smyrnaga.gov/departments/departments/community-relations",
    type: SourceType.GOVERNMENT,
    section: SourceSection.EVENTS,
    city: "Smyrna",
    county: "Cobb",
    active: true,
    scrapeFrequency: "manual",
    notes: "Official source that may surface local public events and notices.",
  },
  {
    name: "Smyrna events",
    url: "https://www.cobbcountyevents.com/calendar/smyrna-events/",
    type: SourceType.CALENDAR,
    section: SourceSection.EVENTS,
    city: "Smyrna",
    county: "Cobb",
    active: true,
    scrapeFrequency: "daily",
    notes: "City-specific Cobb events listing.",
  },
  {
    name: "City of Smyrna Instagram/manual source",
    url: "https://www.instagram.com/cityofsmyrnaga/",
    type: SourceType.MANUAL,
    section: SourceSection.EVENTS,
    city: "Smyrna",
    county: "Cobb",
    active: true,
    scrapeFrequency: "manual",
    notes: "Instagram/manual review source only.",
  },
  {
    name: "City of Powder Springs events and recreation",
    url: "https://www.powderspringsga.gov/578/Events-Recreation-Programs",
    type: SourceType.RECREATION,
    section: SourceSection.EVENTS,
    city: "Powder Springs",
    county: "Cobb",
    active: true,
    scrapeFrequency: "daily",
    notes: "Official events and recreation source.",
  },
  {
    name: "City of Powder Springs calendar",
    url: "https://www.powderspringsga.gov/calendar.aspx",
    type: SourceType.CALENDAR,
    section: SourceSection.MEETINGS,
    city: "Powder Springs",
    county: "Cobb",
    active: true,
    scrapeFrequency: "daily",
    notes: "Official city calendar source.",
  },
  {
    name: "Downtown Powder Springs events",
    url: "https://www.downtownpowdersprings.org/events",
    type: SourceType.CALENDAR,
    section: SourceSection.EVENTS,
    city: "Powder Springs",
    county: "Cobb",
    active: true,
    scrapeFrequency: "weekly",
    notes: "Downtown events source.",
  },
  {
    name: "City of Powder Springs Facebook",
    url: "https://www.facebook.com/cityofpowdersprings/",
    type: SourceType.FACEBOOK,
    section: SourceSection.EVENTS,
    city: "Powder Springs",
    county: "Cobb",
    active: true,
    scrapeFrequency: "manual",
    notes: "Manual review source only.",
  },
  {
    name: "National Weather Service alerts",
    url: "https://api.weather.gov/alerts/active?area=GA",
    type: SourceType.GOVERNMENT,
    section: SourceSection.ALERTS,
    city: null,
    county: "Georgia",
    active: true,
    scrapeFrequency: "hourly",
    notes: "Official NWS watches, warnings, and advisories filtered to covered counties.",
  },
];

async function main() {
  await prisma.scrapeLog.deleteMany();
  await prisma.subscriber.deleteMany();
  await prisma.submittedEvent.deleteMany();
  await prisma.alert.deleteMany();
  await prisma.meeting.deleteMany();
  await prisma.volunteerOpportunity.deleteMany();
  await prisma.event.deleteMany();
  await prisma.source.deleteMany();

  for (const source of sources) {
    await prisma.source.create({ data: source });
  }

  const sourceMap = Object.fromEntries((await prisma.source.findMany()).map((source) => [source.name, source]));

  await prisma.event.createMany({
    data: [
      {
        title: "Family Movie Night at Sara Babb Park",
        description: "Bring lawn chairs and blankets for a family movie night with concessions and activities before sunset.",
        startDateTime: new Date("2026-07-10T19:00:00-04:00"),
        endDateTime: new Date("2026-07-10T22:00:00-04:00"),
        locationName: "Sara Babb Park",
        address: "1200 Babb Lake Road",
        city: "Dallas",
        county: "Paulding",
        category: Category.FAMILY,
        tags: JSON.stringify(["movie night", "outdoor", "summer"]),
        cost: "Free",
        isFree: true,
        isKidFriendly: true,
        isOutdoor: true,
        sourceName: "Paulding County Parks calendar",
        sourceUrl: sourceMap["Paulding County Parks calendar"].url,
        originalUrl: sourceMap["Paulding County Parks calendar"].url,
        status: EventStatus.APPROVED,
        confidenceScore: 0.96,
        sourceId: sourceMap["Paulding County Parks calendar"].id,
      },
      {
        title: "Downtown Dallas Food Truck Friday",
        description: "A downtown evening with food trucks, live acoustic music, and kid-friendly lawn games.",
        startDateTime: new Date("2026-07-11T18:00:00-04:00"),
        endDateTime: new Date("2026-07-11T21:30:00-04:00"),
        locationName: "Downtown Dallas Square",
        address: "Main Street",
        city: "Dallas",
        county: "Paulding",
        category: Category.FOOD_DRINK,
        tags: JSON.stringify(["food trucks", "live music", "downtown"]),
        cost: "Free entry; pay for food",
        isFree: true,
        isKidFriendly: true,
        isOutdoor: true,
        sourceName: "City of Dallas official events page",
        sourceUrl: sourceMap["City of Dallas official events page"].url,
        originalUrl: sourceMap["City of Dallas official events page"].url,
        status: EventStatus.APPROVED,
        confidenceScore: 0.92,
        sourceId: sourceMap["City of Dallas official events page"].id,
      },
      {
        title: "Cedartown Library Summer Storytime",
        description: "Weekly storytime for young readers with crafts and a simple take-home reading activity.",
        startDateTime: new Date("2026-07-09T10:30:00-04:00"),
        endDateTime: new Date("2026-07-09T11:30:00-04:00"),
        locationName: "Cedartown Public Library",
        address: "245 East Avenue",
        city: "Cedartown",
        county: "Polk",
        category: Category.LIBRARY,
        tags: JSON.stringify(["library", "storytime", "kids"]),
        cost: "Free",
        isFree: true,
        isKidFriendly: true,
        isOutdoor: false,
        sourceName: "Downtown Cedartown events page",
        sourceUrl: sourceMap["Downtown Cedartown events page"].url,
        originalUrl: sourceMap["Downtown Cedartown events page"].url,
        status: EventStatus.APPROVED,
        confidenceScore: 0.88,
        sourceId: sourceMap["Downtown Cedartown events page"].id,
      },
      {
        title: "Hiram Community Cleanup Day",
        description: "Volunteers will meet for a cleanup along major neighborhood corridors and the city park trail.",
        startDateTime: new Date("2026-07-18T08:00:00-04:00"),
        endDateTime: new Date("2026-07-18T11:30:00-04:00"),
        locationName: "Hiram City Hall",
        address: "217 Main Street",
        city: "Hiram",
        county: "Paulding",
        category: Category.VOLUNTEER,
        tags: JSON.stringify(["cleanup", "community service", "outdoor"]),
        cost: "Free",
        isFree: true,
        isKidFriendly: true,
        isOutdoor: true,
        sourceName: "City of Hiram official site",
        sourceUrl: sourceMap["City of Hiram official site"].url,
        originalUrl: sourceMap["City of Hiram official site"].url,
        status: EventStatus.APPROVED,
        confidenceScore: 0.86,
        sourceId: sourceMap["City of Hiram official site"].id,
      },
      {
        title: "Rockmart Summer Concert on the Lawn",
        description: "An evening concert with local musicians, food vendors, and a family activity zone.",
        startDateTime: new Date("2026-07-16T18:30:00-04:00"),
        endDateTime: new Date("2026-07-16T21:00:00-04:00"),
        locationName: "Rockmart Depot Park",
        address: "118 North Marble Street",
        city: "Rockmart",
        county: "Polk",
        category: Category.MUSIC,
        tags: JSON.stringify(["concert", "live music", "outdoor"]),
        cost: "$5 suggested donation",
        isFree: false,
        isKidFriendly: true,
        isOutdoor: true,
        sourceName: "City of Rockmart official site",
        sourceUrl: sourceMap["City of Rockmart official site"].url,
        originalUrl: sourceMap["City of Rockmart official site"].url,
        status: EventStatus.APPROVED,
        confidenceScore: 0.93,
        sourceId: sourceMap["City of Rockmart official site"].id,
      },
      {
        title: "Woodstock Summer Street Fest",
        description: "A downtown evening with vendors, family activities, and live music throughout the district.",
        startDateTime: new Date("2026-07-17T17:00:00-04:00"),
        endDateTime: new Date("2026-07-17T21:00:00-04:00"),
        locationName: "Downtown Woodstock",
        address: "8588 Main Street",
        city: "Woodstock",
        county: "Cherokee",
        category: Category.FESTIVAL,
        tags: JSON.stringify(["downtown", "vendors", "family"]),
        cost: "Free",
        isFree: true,
        isKidFriendly: true,
        isOutdoor: true,
        sourceName: "City of Woodstock special events",
        sourceUrl: sourceMap["City of Woodstock special events"].url,
        originalUrl: sourceMap["City of Woodstock special events"].url,
        status: EventStatus.APPROVED,
        confidenceScore: 0.82,
        sourceId: sourceMap["City of Woodstock special events"].id,
      },
      {
        title: "Marietta Square Art Walk",
        description: "An evening art walk with live music, gallery specials, and local food options around the square.",
        startDateTime: new Date("2026-07-12T18:00:00-04:00"),
        endDateTime: new Date("2026-07-12T21:00:00-04:00"),
        locationName: "Marietta Square",
        address: "Historic Marietta Square",
        city: "Marietta",
        county: "Cobb",
        category: Category.MUSIC,
        tags: JSON.stringify(["art walk", "square", "evening"]),
        cost: "Free",
        isFree: true,
        isKidFriendly: true,
        isOutdoor: true,
        sourceName: "Visit Marietta events",
        sourceUrl: sourceMap["Visit Marietta events"].url,
        originalUrl: sourceMap["Visit Marietta events"].url,
        status: EventStatus.APPROVED,
        confidenceScore: 0.8,
        sourceId: sourceMap["Visit Marietta events"].id,
      },
      {
        title: "The Mill Night Market",
        description: "A community night market with makers, food stalls, and live entertainment at The Mill on Etowah.",
        startDateTime: new Date("2026-07-19T18:00:00-04:00"),
        endDateTime: new Date("2026-07-19T21:30:00-04:00"),
        locationName: "The Mill on Etowah",
        address: "225 Reformation Parkway",
        city: "Canton",
        county: "Cherokee",
        category: Category.FOOD_DRINK,
        tags: JSON.stringify(["night market", "makers", "food"]),
        cost: "Free entry",
        isFree: true,
        isKidFriendly: true,
        isOutdoor: false,
        sourceName: "The Mill on Etowah events",
        sourceUrl: sourceMap["The Mill on Etowah events"].url,
        originalUrl: sourceMap["The Mill on Etowah events"].url,
        status: EventStatus.APPROVED,
        confidenceScore: 0.79,
        sourceId: sourceMap["The Mill on Etowah events"].id,
      },
      {
        title: "Adairsville Depot Day",
        description: "A community day with heritage activities, food vendors, and family-friendly performances.",
        startDateTime: new Date("2026-07-25T10:00:00-04:00"),
        endDateTime: new Date("2026-07-25T16:00:00-04:00"),
        locationName: "Downtown Adairsville",
        address: "Public Square",
        city: "Adairsville",
        county: "Bartow",
        category: Category.FAMILY,
        tags: JSON.stringify(["heritage", "vendors", "family"]),
        cost: "Free",
        isFree: true,
        isKidFriendly: true,
        isOutdoor: true,
        sourceName: "City of Adairsville events",
        sourceUrl: sourceMap["City of Adairsville events"].url,
        originalUrl: sourceMap["City of Adairsville events"].url,
        status: EventStatus.APPROVED,
        confidenceScore: 0.77,
        sourceId: sourceMap["City of Adairsville events"].id,
      },
      {
        title: "Trivia Tuesday at Pizza Shack",
        description: "A casual community trivia night with prizes for the top teams.",
        startDateTime: new Date("2026-07-14T19:00:00-04:00"),
        endDateTime: new Date("2026-07-14T21:00:00-04:00"),
        locationName: "Pizza Shack",
        address: "110 Elm Street",
        city: "Rockmart",
        county: "Polk",
        category: Category.TRIVIA,
        tags: JSON.stringify(["trivia", "restaurant", "team event"]),
        cost: "Free to play",
        isFree: true,
        isKidFriendly: false,
        isOutdoor: false,
        sourceName: "Pizza Shack Facebook",
        sourceUrl: sourceMap["Pizza Shack Facebook"].url,
        originalUrl: sourceMap["Pizza Shack Facebook"].url,
        status: EventStatus.PENDING,
        confidenceScore: 0.56,
        sourceId: sourceMap["Pizza Shack Facebook"].id,
      },
    ],
  });

  await prisma.alert.createMany({
    data: [
      {
        title: "Severe thunderstorm watch for local counties",
        description: "Residents should monitor local forecasts and secure outdoor items this evening.",
        alertType: AlertType.SEVERE_WEATHER,
        severity: AlertSeverity.HIGH,
        city: null,
        county: "Paulding",
        sourceName: "Paulding County Sheriff Facebook",
        sourceUrl: sourceMap["Paulding County Sheriff Facebook"].url,
        originalUrl: sourceMap["Paulding County Sheriff Facebook"].url,
        startsAt: new Date("2026-07-06T15:00:00-04:00"),
        expiresAt: new Date("2026-07-07T00:00:00-04:00"),
        status: AlertStatus.ACTIVE,
        sourceId: sourceMap["Paulding County Sheriff Facebook"].id,
      },
      {
        title: "Dallas utility work traffic shift",
        description: "Single-lane traffic is in effect near downtown while utility crews complete repairs.",
        alertType: AlertType.TRAFFIC,
        severity: AlertSeverity.MEDIUM,
        city: "Dallas",
        county: "Paulding",
        locationName: "Main Street corridor",
        address: "Downtown Dallas",
        sourceName: "Dallas Police Facebook",
        sourceUrl: sourceMap["Dallas Police Facebook"].url,
        originalUrl: sourceMap["Dallas Police Facebook"].url,
        startsAt: new Date("2026-07-06T08:00:00-04:00"),
        expiresAt: new Date("2026-07-08T18:00:00-04:00"),
        status: AlertStatus.ACTIVE,
        sourceId: sourceMap["Dallas Police Facebook"].id,
      },
      {
        title: "Marietta square detour for weekend event setup",
        description: "Drivers should expect temporary lane shifts near the square while crews prepare for a special event.",
        alertType: AlertType.ROAD_CLOSURE,
        severity: AlertSeverity.MEDIUM,
        city: "Marietta",
        county: "Cobb",
        locationName: "Marietta Square",
        address: "Downtown Marietta",
        sourceName: "Cobb County Government Facebook",
        sourceUrl: sourceMap["Cobb County Government Facebook"].url,
        originalUrl: sourceMap["Cobb County Government Facebook"].url,
        startsAt: new Date("2026-07-10T08:00:00-04:00"),
        expiresAt: new Date("2026-07-12T23:00:00-04:00"),
        status: AlertStatus.ACTIVE,
        sourceId: sourceMap["Cobb County Government Facebook"].id,
      },
      {
        title: "Rockmart boil water advisory lifted",
        description: "The advisory has ended after testing confirmed normal water quality.",
        alertType: AlertType.BOIL_WATER_ADVISORY,
        severity: AlertSeverity.LOW,
        city: "Rockmart",
        county: "Polk",
        sourceName: "Rockmart Police Facebook",
        sourceUrl: sourceMap["Rockmart Police Facebook"].url,
        originalUrl: sourceMap["Rockmart Police Facebook"].url,
        startsAt: new Date("2026-07-01T10:00:00-04:00"),
        expiresAt: new Date("2026-07-03T18:00:00-04:00"),
        status: AlertStatus.EXPIRED,
        sourceId: sourceMap["Rockmart Police Facebook"].id,
      },
    ],
  });

  await prisma.meeting.createMany({
    data: [
      {
        title: "Paulding County Board of Commissioners Work Session",
        governmentBody: "Paulding County Board of Commissioners",
        meetingType: MeetingType.COUNTY_COMMISSION,
        startDateTime: new Date("2026-07-09T10:00:00-04:00"),
        endDateTime: new Date("2026-07-09T12:00:00-04:00"),
        locationName: "BOC Meeting Room",
        address: "240 Constitution Boulevard",
        city: "Dallas",
        county: "Paulding",
        agendaUrl: "https://www.paulding.gov/",
        sourceName: "Paulding County Board of Commissioners meetings",
        sourceUrl: sourceMap["Paulding County Board of Commissioners meetings"].url,
        originalUrl: sourceMap["Paulding County Board of Commissioners meetings"].url,
        status: MeetingStatus.UPCOMING,
        summary: "Work session covering transportation updates, parks capital planning, and budget calendar items.",
        plainEnglishSummary:
          "County leaders are expected to discuss road work timing, parks upgrades, and the next steps in the budget process.",
        keyTopics: JSON.stringify(["roads", "parks improvements", "budget planning"]),
        whyResidentsCare:
          "These discussions shape future road projects, recreation funding, and how quickly county services can respond to growth.",
        sourceId: sourceMap["Paulding County Board of Commissioners meetings"].id,
      },
      {
        title: "Rockmart City Council Meeting",
        governmentBody: "Rockmart City Council",
        meetingType: MeetingType.CITY_COUNCIL,
        startDateTime: new Date("2026-07-13T18:00:00-04:00"),
        endDateTime: new Date("2026-07-13T19:30:00-04:00"),
        locationName: "Rockmart City Hall",
        address: "316 North Piedmont Avenue",
        city: "Rockmart",
        county: "Polk",
        agendaUrl: "https://www.rockmart-ga.gov/",
        sourceName: "City of Rockmart public meetings",
        sourceUrl: sourceMap["City of Rockmart public meetings"].url,
        originalUrl: sourceMap["City of Rockmart public meetings"].url,
        status: MeetingStatus.UPCOMING,
        summary: "Expected agenda items include downtown parking, public works updates, and special event permits.",
        plainEnglishSummary:
          "Council members are expected to review parking, public works updates, and approvals tied to downtown events.",
        keyTopics: JSON.stringify(["parking", "public works", "special events"]),
        whyResidentsCare:
          "Parking rules, street maintenance, and event approvals can affect downtown traffic and neighborhood access.",
        sourceId: sourceMap["City of Rockmart public meetings"].id,
      },
      {
        title: "Marietta City Council Agenda Session",
        governmentBody: "Marietta City Council",
        meetingType: MeetingType.CITY_COUNCIL,
        startDateTime: new Date("2026-07-14T18:00:00-04:00"),
        endDateTime: new Date("2026-07-14T20:00:00-04:00"),
        locationName: "Marietta City Hall",
        address: "205 Lawrence Street NE",
        city: "Marietta",
        county: "Cobb",
        agendaUrl: "https://www.mariettaga.gov/Calendar.aspx",
        sourceName: "City of Marietta calendar",
        sourceUrl: sourceMap["City of Marietta calendar"].url,
        originalUrl: sourceMap["City of Marietta calendar"].url,
        status: MeetingStatus.UPCOMING,
        summary: "Council is expected to review event permits, downtown mobility updates, and budget adjustments.",
        plainEnglishSummary:
          "City leaders are expected to discuss downtown traffic, event permits, and budget changes that affect city services.",
        keyTopics: JSON.stringify(["budget adjustments", "mobility", "event permits"]),
        whyResidentsCare:
          "These agenda items can affect daily traffic patterns, public spending priorities, and how community events are approved.",
        sourceId: sourceMap["City of Marietta calendar"].id,
      },
      {
        title: "Cherokee County Community Meeting Calendar Review",
        governmentBody: "Cherokee County Government",
        meetingType: MeetingType.COUNTY_COMMISSION,
        startDateTime: new Date("2026-07-15T17:30:00-04:00"),
        endDateTime: new Date("2026-07-15T19:00:00-04:00"),
        locationName: "Cherokee County Administration Building",
        address: "1130 Bluffs Parkway",
        city: "Canton",
        county: "Cherokee",
        agendaUrl: "https://cherokeega.com/cherokee-county-events.php",
        sourceName: "Cherokee County events and meetings",
        sourceUrl: sourceMap["Cherokee County events and meetings"].url,
        originalUrl: sourceMap["Cherokee County events and meetings"].url,
        status: MeetingStatus.UPCOMING,
        summary: "County leaders are expected to review upcoming public hearing dates, parks updates, and service scheduling items.",
        plainEnglishSummary:
          "This meeting is expected to cover county service timing, parks updates, and the schedule for upcoming public hearings.",
        keyTopics: JSON.stringify(["parks updates", "public hearing schedule", "service timing"]),
        whyResidentsCare:
          "Meeting schedules and county service decisions affect how residents plan around hearings, recreation programs, and public access.",
        sourceId: sourceMap["Cherokee County events and meetings"].id,
      },
    ],
  });

  await prisma.volunteerOpportunity.createMany({
    data: [
      {
        title: "Back-to-School Supply Sorting",
        organization: "Paulding School Support Coalition",
        description: "Help sort donated school supplies and pack classroom kits for local students.",
        dateTime: new Date("2026-07-12T09:00:00-04:00"),
        locationName: "New Hope Community Center",
        address: "456 Support Drive",
        city: "Dallas",
        county: "Paulding",
        category: "School support",
        contactName: "Kim Rogers",
        contactEmail: "volunteer@example.org",
        sourceName: "Manual community source",
        sourceUrl: "/admin",
        status: VolunteerStatus.OPEN,
      },
      {
        title: "Animal Shelter Laundry and Enrichment Team",
        organization: "Polk Animal Services",
        description: "A recurring volunteer shift for laundry, kennel support, and simple dog enrichment.",
        dateTime: new Date("2026-07-15T14:00:00-04:00"),
        locationName: "Animal Shelter",
        address: "171 Animal Shelter Lane",
        city: "Cedartown",
        county: "Polk",
        category: "Animal shelter",
        contactName: "Staff team",
        contactEmail: "animals@example.org",
        sourceName: "Manual community source",
        sourceUrl: "/admin",
        status: VolunteerStatus.OPEN,
      },
      {
        title: "Woodstock Greenway Cleanup",
        organization: "Woodstock Community Volunteers",
        description: "Join a morning cleanup along the greenway and nearby public spaces.",
        dateTime: new Date("2026-07-20T08:30:00-04:00"),
        locationName: "Woofstock Park Trailhead",
        address: "101 Arnold Mill Road",
        city: "Woodstock",
        county: "Cherokee",
        category: "Cleanup",
        contactName: "Volunteer desk",
        contactEmail: "woodstock@example.org",
        sourceName: "Manual community source",
        sourceUrl: "/admin",
        status: VolunteerStatus.OPEN,
      },
      {
        title: "Marietta Pantry Restock",
        organization: "Marietta Community Pantry",
        description: "Help receive, sort, and shelve pantry items for the week ahead.",
        dateTime: new Date("2026-07-18T09:00:00-04:00"),
        locationName: "Community Pantry",
        address: "99 Service Lane",
        city: "Marietta",
        county: "Cobb",
        category: "Food pantry",
        contactName: "Outreach team",
        contactEmail: "marietta@example.org",
        sourceName: "Manual community source",
        sourceUrl: "/admin",
        status: VolunteerStatus.OPEN,
      },
    ],
  });

  await prisma.submittedEvent.createMany({
    data: [
      {
        submitterName: "Jamie Thomas",
        submitterEmail: "jamie@example.com",
        submissionType: SubmissionType.EVENT,
        title: "Neighborhood Ice Cream Social",
        description: "A small community meetup for families at the playground pavilion.",
        startDateTime: new Date("2026-07-20T18:30:00-04:00"),
        endDateTime: new Date("2026-07-20T20:00:00-04:00"),
        locationName: "Pine Ridge Playground",
        address: "12 Pine Ridge Lane",
        city: "Hiram",
        county: "Paulding",
        category: Category.FAMILY,
        cost: "Free",
        sourceUrl: "",
        status: SubmittedEventStatus.PENDING,
      },
      {
        submitterName: "Alex Greene",
        submitterEmail: "alex@example.com",
        submissionType: SubmissionType.VOLUNTEER,
        title: "Weekend pantry shelf restock",
        description: "Looking for 6 volunteers to help receive and sort pantry donations.",
        startDateTime: new Date("2026-07-19T09:00:00-04:00"),
        endDateTime: new Date("2026-07-19T12:00:00-04:00"),
        locationName: "Cedartown Community Pantry",
        address: "18 Mercy Way",
        city: "Cedartown",
        county: "Polk",
        category: Category.VOLUNTEER,
        cost: "Free",
        sourceUrl: "",
        status: SubmittedEventStatus.PENDING,
      },
      {
        submitterName: "Morgan Hall",
        submitterEmail: "morgan@example.com",
        submissionType: SubmissionType.ACTIVITY,
        title: "Kennesaw board game night",
        description: "A casual bring-your-own-board-games meetup at a local coffee shop.",
        startDateTime: new Date("2026-07-22T18:30:00-04:00"),
        endDateTime: new Date("2026-07-22T21:00:00-04:00"),
        locationName: "Main Street Coffee",
        address: "22 Main Street",
        city: "Kennesaw",
        county: "Cobb",
        category: Category.TRIVIA,
        cost: "Free",
        sourceUrl: "",
        status: SubmittedEventStatus.PENDING,
      },
    ],
  });

  await prisma.subscriber.createMany({
    data: [
      {
        email: "familydigest@example.com",
        city: "Dallas",
        county: "Paulding",
        interests: JSON.stringify(["Family", "Free Events", "Food & Drink"]),
        active: true,
      },
      {
        email: "civicwatch@example.com",
        city: "Cedartown",
        county: "Polk",
        interests: JSON.stringify(["Public Meetings", "Alerts", "Volunteer"]),
        active: true,
      },
      {
        email: "woodstockweekly@example.com",
        city: "Woodstock",
        county: "Cherokee",
        interests: JSON.stringify(["Music", "Family", "Public Meetings"]),
        active: true,
      },
      {
        email: "cobbcalendar@example.com",
        city: "Marietta",
        county: "Cobb",
        interests: JSON.stringify(["Free Events", "Alerts", "Food & Drink"]),
        active: true,
      },
    ],
  });

  await prisma.scrapeLog.createMany({
    data: [
      {
        sourceId: sourceMap["Paulding County Parks calendar"].id,
        sourceName: "Paulding County Parks calendar",
        status: "SUCCESS",
        message: "Seeded sample scrape log entry.",
        itemsFound: 4,
        itemsCreated: 2,
        itemsUpdated: 2,
      },
      {
        sourceId: sourceMap["City of Hiram Facebook"].id,
        sourceName: "City of Hiram Facebook",
        status: "PARTIAL",
        message: "Manual review source seeded without automated scraping.",
        itemsFound: 0,
        itemsCreated: 0,
        itemsUpdated: 0,
      },
      {
        sourceId: sourceMap["Cobb County Government Facebook"].id,
        sourceName: "Cobb County Government Facebook",
        status: "PARTIAL",
        message: "Manual review source seeded without automated scraping.",
        itemsFound: 0,
        itemsCreated: 0,
        itemsUpdated: 0,
      },
    ],
  });
}

main()
  .catch((error) => {
    console.error(error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
